### PR TITLE
Change "tee - a ..." to "tee -a ..."

### PR DESCRIPTION
**Pull request by tst-jlarocco**
Fixes a very annoying bug in the Linux install instructions.

### CODE REVIEW

**Comment by tst-jlarocco** [comment]
Blah.  Want to check with my employer before agreeing to the CLA.  Will likely accept in the morning.

**Comment by tst-jlarocco** [comment]
Also, while restoring the original sources.list on my machine, it dawned on me that a better fix would be to write this to /etc/apt/sources.list.d/gauge.list instead of the main sources.list

**Comment by sriv** [comment]
FWIW, we are moving away from bintray to github package repository. I don't think they support deb/rpm yet.

**Comment by nehashri** [comment]
@tst-jlarocco were you able to as your employer about signing the CLA?

**Pull request closed without merging**
